services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=portal_capacitaciones'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
